# Generated by Django 4.0.5 on 2022-06-10 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 6, 10, 13, 11, 7, 760406)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 6, 10, 13, 11, 7, 760551)),
        ),
    ]
