# Generated by Django 4.0.5 on 2022-06-10 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatBackend', '0003_alter_chat_created_at_alter_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 13, 16, 10, 629611, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 13, 16, 10, 629889, tzinfo=utc)),
        ),
    ]
